import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {


  const handleClick = () => {
    console.log('placing your order')



  }
  return (
    <div className={styles.container}>
      <Head>
        <title>My Webbsite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
      <ul>
      <Link href="/blog"><li>Blog</li></Link>
      <Link href="/blog/first"><li>First blog page</li></Link>
      </ul>

      <button onClick={() => handleClick()}>Place order</button>

    
    </div>
  )
}
